[package]
name = "cel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8.0"
bevy_basic_camera = {git = "https://github.com/DGriffin91/bevy_basic_camera"}